package com.tqlab.demo.dal.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.tqlab.demo.dal.dataobject.Movies;

public class MoviesSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOVIES
     *
     * @mbggenerated
     */
    public String insertSelective(Movies record) {
        BEGIN();
        INSERT_INTO("MOVIES");
        
        if (record.getMovieid() != null) {
            VALUES("MOVIEID", "#{movieid,jdbcType=INTEGER}");
        }
        
        if (record.getStarid() != null) {
            VALUES("STARID", "#{starid,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            VALUES("TITLE", "#{title,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOVIES
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(Movies record) {
        BEGIN();
        UPDATE("MOVIES");
        
        if (record.getStarid() != null) {
            SET("STARID = #{starid,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            SET("TITLE = #{title,jdbcType=VARCHAR}");
        }
        
        WHERE("MOVIEID = #{movieid,jdbcType=INTEGER}");
        
        return SQL();
    }
}