package com.tqlab.demo.dal.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.tqlab.demo.dal.dataobject.Star;

public class StarSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated
     */
    public String insertSelective(Star record) {
        BEGIN();
        INSERT_INTO("STAR");
        
        if (record.getId() != null) {
            VALUES("ID", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getFirstname() != null) {
            VALUES("FIRSTNAME", "#{firstname,jdbcType=VARCHAR}");
        }
        
        if (record.getLastname() != null) {
            VALUES("LASTNAME", "#{lastname,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(Star record) {
        BEGIN();
        UPDATE("STAR");
        
        if (record.getFirstname() != null) {
            SET("FIRSTNAME = #{firstname,jdbcType=VARCHAR}");
        }
        
        if (record.getLastname() != null) {
            SET("LASTNAME = #{lastname,jdbcType=VARCHAR}");
        }
        
        WHERE("ID = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}