package com.tqlab.demo.dal.dataobject;

import java.io.Serializable;

public class MoviesKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOVIES.MOVIEID
     *
     * @mbggenerated
     */
    private Integer movieid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MOVIES
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOVIES.MOVIEID
     *
     * @return the value of MOVIES.MOVIEID
     *
     * @mbggenerated
     */
    public Integer getMovieid() {
        return movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOVIES.MOVIEID
     *
     * @param movieid the value for MOVIES.MOVIEID
     *
     * @mbggenerated
     */
    public void setMovieid(Integer movieid) {
        this.movieid = movieid;
    }
}