package com.tqlab.demo.dal.dataobject;

import java.io.Serializable;

public class Movies extends MoviesKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOVIES.STARID
     *
     * @mbggenerated
     */
    private Integer starid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOVIES.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MOVIES
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOVIES.STARID
     *
     * @return the value of MOVIES.STARID
     *
     * @mbggenerated
     */
    public Integer getStarid() {
        return starid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOVIES.STARID
     *
     * @param starid the value for MOVIES.STARID
     *
     * @mbggenerated
     */
    public void setStarid(Integer starid) {
        this.starid = starid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOVIES.TITLE
     *
     * @return the value of MOVIES.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOVIES.TITLE
     *
     * @param title the value for MOVIES.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}