package com.tqlab.demo.dal.dataobject;

import java.io.Serializable;

public class Star extends StarKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR.FIRSTNAME
     *
     * @mbggenerated
     */
    private String firstname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR.LASTNAME
     *
     * @mbggenerated
     */
    private String lastname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table STAR
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR.FIRSTNAME
     *
     * @return the value of STAR.FIRSTNAME
     *
     * @mbggenerated
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR.FIRSTNAME
     *
     * @param firstname the value for STAR.FIRSTNAME
     *
     * @mbggenerated
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname == null ? null : firstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR.LASTNAME
     *
     * @return the value of STAR.LASTNAME
     *
     * @mbggenerated
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR.LASTNAME
     *
     * @param lastname the value for STAR.LASTNAME
     *
     * @mbggenerated
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }
}