package com.tqlab.demo.dal.dataobject;

import java.io.Serializable;

public class StarMovies2 implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator plugin (SqlTemplatePlugin).
     * This field corresponds to the database table star_id
     *
    @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator plugin (SqlTemplatePlugin).
     * This field corresponds to the database table name
     *
    @mbggenerated
     */
    private String firstname;

    /**
     * This field was generated by MyBatis Generator plugin (SqlTemplatePlugin).
     * This field corresponds to the database table lastname
     *
    @mbggenerated
     */
    private String lastname;

    /**
     * This field was generated by MyBatis Generator plugin (SqlTemplatePlugin).
     * This field corresponds to the database table movieid
     *
    @mbggenerated
     */
    private Integer movieid;

    /**
     * This field was generated by MyBatis Generator plugin (SqlTemplatePlugin).
     * This field corresponds to the database table title
     *
    @mbggenerated
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator plugin (SqlTemplatePlugin).
     * This method corresponds to the database table star_id
     *
    @mbggenerated
     */
    public void setId(Integer id) {
        this.id=id;
    }

    /**
     * This method was generated by MyBatis Generator plugin (SqlTemplatePlugin).
     * This method corresponds to the database table star_id
     *
    @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator plugin (SqlTemplatePlugin).
     * This method corresponds to the database table name
     *
    @mbggenerated
     */
    public void setFirstname(String firstname) {
        this.firstname=firstname;
    }

    /**
     * This method was generated by MyBatis Generator plugin (SqlTemplatePlugin).
     * This method corresponds to the database table name
     *
    @mbggenerated
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator plugin (SqlTemplatePlugin).
     * This method corresponds to the database table lastname
     *
    @mbggenerated
     */
    public void setLastname(String lastname) {
        this.lastname=lastname;
    }

    /**
     * This method was generated by MyBatis Generator plugin (SqlTemplatePlugin).
     * This method corresponds to the database table lastname
     *
    @mbggenerated
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator plugin (SqlTemplatePlugin).
     * This method corresponds to the database table movieid
     *
    @mbggenerated
     */
    public void setMovieid(Integer movieid) {
        this.movieid=movieid;
    }

    /**
     * This method was generated by MyBatis Generator plugin (SqlTemplatePlugin).
     * This method corresponds to the database table movieid
     *
    @mbggenerated
     */
    public Integer getMovieid() {
        return movieid;
    }

    /**
     * This method was generated by MyBatis Generator plugin (SqlTemplatePlugin).
     * This method corresponds to the database table title
     *
    @mbggenerated
     */
    public void setTitle(String title) {
        this.title=title;
    }

    /**
     * This method was generated by MyBatis Generator plugin (SqlTemplatePlugin).
     * This method corresponds to the database table title
     *
    @mbggenerated
     */
    public String getTitle() {
        return title;
    }
}